name: documentation checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./documentation
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Lint
        run: make lint

      - name: Build
        run: make build
      
      - name: Test
        run: make test
